### ISSUE TITLE
LiteFlow documentation discussion

### ISSUE THREAD

**Issue by bryan31** [dromara/liteflow#9]

**Comment by MonkSoul** [comment]
支持大佬

**Comment by bryan31** [comment]
这是第一条评论，大家对文档有什么问题，可以在这里评论！

**Comment by JasonWong-ZS** [comment]
第三个

**Comment by mySingleLive** [comment]
大佬牛逼

**Comment by honestyallan** [comment]
点赞

**Comment by MrJackBack** [comment]
大佬可以出一个基于SpringBoot稍微复杂点流程配置的案例吗

**Comment by bryan31** [comment]
> @MrJackBack
> 大佬可以出一个基于SpringBoot稍微复杂点流程配置的案例吗

可以的，到时候我再testcase里写一个复杂点的

**Comment by MrJackBack** [comment]
感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月16日(星期四) 中午11:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dromara/liteflow] LiteFlow documentation discussion (Issue #9)





  
@MrJackBack
 大佬可以出一个基于SpringBoot稍微复杂点流程配置的案例吗
  
可以的，到时候我再testcase里写一个复杂点的
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KingCesc** [comment]
com.yomahub.liteflow.spring.ComponentScaner ->
com.yomahub.liteflow.spring.ComponentScanner

**Comment by KingCesc** [comment]
whenMaxWaitSecond-> whenMaxWaitSeconds

**Comment by bryan31** [comment]
> @KingCesc
> com.yomahub.liteflow.spring.ComponentScaner ->
> com.yomahub.liteflow.spring.ComponentScanner

这个在最新版本中名字已经更改过了哦

**Comment by abbothzhang** [comment]
为什么要新增pre 和 finally组件？

**Comment by bryan31** [comment]
> @abbothzhang
> 为什么要新增pre 和 finally组件？

因为小伙伴使用过程中有前置和后置的需求

**Comment by abbothzhang** [comment]
可以在xml直接支持嵌套吗，会更方便

**Comment by abbothzhang** [comment]
> @bryan31
> > @abbothzhang
> > 为什么要新增pre 和 finally组件？
> 
> 因为小伙伴使用过程中有前置和后置的需求

xml里位置放到前面不就可以了吗

**Comment by bryan31** [comment]
> @abbothzhang
> 可以在xml直接支持嵌套吗，会更方便

chain可以嵌套

**Comment by bryan31** [comment]
> @abbothzhang
> > @bryan31
> > > @abbothzhang
> > > 为什么要新增pre 和 finally组件？
> > 
> > 因为小伙伴使用过程中有前置和后置的需求
> 
> xml里位置放到前面不就可以了吗

是的，放到前面的确可以。但是这个issue主要是做后置的，后置的并不是放到后面就可以的。因为后置如同java的finally，最终总会执行。因为做了finally，所以一并把pre也给做了，pre从某种意义上来说，的确显得有点鸡肋

**Comment by abbothzhang** [comment]
> @bryan31
> > @abbothzhang
> > > @bryan31
> > > > @abbothzhang
> > > > 为什么要新增pre 和 finally组件？
> > > 
> > > 因为小伙伴使用过程中有前置和后置的需求
> > 
> > xml里位置放到前面不就可以了吗
> 
> 是的，放到前面的确可以。但是这个issue主要是做后置的，后置的并不是放到后面就可以的。因为后置如同java的finally，最终总会执行。因为做了finally，所以一并把pre也给做了，pre从某种意义上来说，的确显得有点鸡肋

懂了

**Comment by miaoxu9999** [comment]
大佬，想问下咱们这个liteFlow支持某种粒度的流程编排吗，比如说，demo中给出的是某种商品价格的编排，那我想按照不同活动，对同一商品进行不同编排，这种怎么去做呢？可以优化一下demo吗？

**Comment by bryan31** [comment]
> @miaoxu9999
> 大佬，想问下咱们这个liteFlow支持某种粒度的流程编排吗，比如说，demo中给出的是某种商品价格的编排，那我想按照不同活动，对同一商品进行不同编排，这种怎么去做呢？可以优化一下demo吗？

这个动态编排可以解决。动态编排可以让开发者通过代码进行编排。这个功能会作为下版本的特性发布。

**Comment by cjs3030** [comment]
步骤打印可以关掉嘛

**Comment by miaoxu9999** [comment]
> @bryan31
> > @miaoxu9999
> > 大佬，想问下咱们这个liteFlow支持某种粒度的流程编排吗，比如说，demo中给出的是某种商品价格的编排，那我想按照不同活动，对同一商品进行不同编排，这种怎么去做呢？可以优化一下demo吗？
> 
> 这个动态编排可以解决。动态编排可以让开发者通过代码进行编排。这个功能会作为下版本的特性发布。

好的，很期待下个版本

**Comment by rguogreen** [comment]
使用全局切面的时候， 想要拿到 组件的 tag，name， 咋个拿法， 仅看到一个nodeid。

**Comment by rguogreen** [comment]
不得不说， 这个东东很好！

**Comment by bryan31** [comment]
> @rguogreen
> 使用全局切面的时候， 想要拿到 组件的 tag，name， 咋个拿法， 仅看到一个nodeid。

目前没法拿到，在gitee上提issue，我会在下个版本加入的

**Comment by mclubing** [comment]
请问支持条件分支吗？

**Comment by chinadeng** [comment]
为什么默认只是单个flow.xml??

**Comment by davidricardo1026** [comment]
能不能不要黑底白字,不是每个人都喜欢黑底白字的,而且黑底白字对比度高,比较费眼

**Comment by bryan31** [comment]
> @mclubing
> 请问支持条件分支吗？

支持的

**Comment by bryan31** [comment]
> @davidricardo1026
> 能不能不要黑底白字,不是每个人都喜欢黑底白字的,而且黑底白字对比度高,比较费眼

在下次官网改版的时候，我会加入白天模式

**Comment by 313988838** [comment]
支持大佬。可以可以.

**Comment by bryan31** [comment]
> @313988838
> 支持大佬。可以可以.

感谢支持！

**Comment by 313988838** [comment]
支持中途中断吗？条件分支有示例吗？

**Comment by 1554833267** [comment]
可以把执行流程配置用JSON的格式存储到数据库，然后读出执行吗，如果可以的话要怎么操作

**Comment by bryan31** [comment]
> @geozhang-fz
> “工作台模式”是不是就是责任链设计模式（Chain of Responsibility Pattern）呀？

有些类似，但不完全相同。你可以这么理解

**Comment by bryan31** [comment]
> @1114902352
> 大佬，麻烦问下liteflow这种场景吗，有两个节点A和B，A是一个普通节点，B是一个动态子流程，B这个子流程里面节点和顺序都是由A来确定，且每次请求这个B里面都有可能改变。我看过平滑热更新和代码动态构造规则，感觉可以实现，但是没有看到有卸载流程的情况。担心动态创建流程过多后会内存溢出。

目前的确没有卸载的情况，但是可以替换，你变化之后替换原流程就可以了。因为卸载涉及到级联的场景。
至于创建过多导致内存溢出，除非你代码中创建几w个流程。一般正常情况下不太可能。

**Comment by 1114902352** [comment]
> @bryan31
> > @1114902352
> > 大佬，麻烦问下liteflow这种场景吗，有两个节点A和B，A是一个普通节点，B是一个动态子流程，B这个子流程里面节点和顺序都是由A来确定，且每次请求这个B里面都有可能改变。我看过平滑热更新和代码动态构造规则，感觉可以实现，但是没有看到有卸载流程的情况。担心动态创建流程过多后会内存溢出。
> 
> 目前的确没有卸载的情况，但是可以替换，你变化之后替换原流程就可以了。因为卸载涉及到级联的场景。
> 至于创建过多导致内存溢出，除非你代码中创建几w个流程。一般正常情况下不太可能。

好的，谢谢啦

**Comment by guyixn** [comment]
## 相同异步并行组之间的抛错 写错了呀
思考以下问题，如果有以下流程，第一个并行组出错还继续，第二个出错不继续。那么如果c报错，会走到e么
代码和文档根本不一致

**Comment by syl-007** [comment]
好东西，支持~

**Comment by bryan31** [comment]
> @guyixn
> ## 相同异步并行组之间的抛错 写错了呀
> 思考以下问题，如果有以下流程，第一个并行组出错还继续，第二个出错不继续。那么如果c报错，会走到e么
> 代码和文档根本不一致

我会详细看一下文档和实际测试用例的，如果有错误，会修正。
希望发现此类问题，以issue的方式提。因为文档评论我不是每天会看，但是issue我每天会处理。感谢

**Comment by guyixn** [comment]
> @bryan31
> > @guyixn
> > ## 相同异步并行组之间的抛错 写错了呀
> > 思考以下问题，如果有以下流程，第一个并行组出错还继续，第二个出错不继续。那么如果c报错，会走到e么
> > 代码和文档根本不一致
> 
> 我会详细看一下文档和实际测试用例的，如果有错误，会修正。
> 希望发现此类问题，以issue的方式提。因为文档评论我不是每天会看，但是issue我每天会处理。感谢

okok,加油加油!!!

**Comment by kaneax** [comment]
能不能列举一个子流程跳转节点和跳转流程id的详细demo

**Comment by bryan31** [comment]
> @kaneax
> 能不能列举一个子流程跳转节点和跳转流程id的详细demo
> 

在源码中有大部分场景的testcase，可以试着跑一下

**Comment by DokiYoloo** [comment]
地铁上就整个文档看完了
足够轻量 赞

**Comment by bryan31** [comment]
> @DokiYoloo
> 地铁上就整个文档看完了
> 足够轻量 赞

感谢关注和支持~

**Comment by zhao-staff-officer** [comment]
支持大佬

**Comment by greamrod** [comment]
支持大佬

**Comment by luopeijie1998** [comment]
nbnbnb支持一波

**Comment by cyf586** [comment]
<chain name="test">
    <when value="a,b"/> 
    <then value="c"/>
</chain>
目前框架无法支持a与b并行执行后，无需等待结果，直接同步执行c的这种应用场景；只能选择同时执行a，b，b，这样会提交3个任务到线程池，而提交任务的本地线程在闲置，对于高并发场景，有一定的性能损失，如果选择部分使用编排，会导致逻辑割裂，代码可读维护性下降，期待后续的改进

**Comment by HengshengZ** [comment]
请问下监控的处理逻辑能在哪里看到呢

**Comment by bryan31** [comment]
> @cyf586
> 目前框架无法支持a与b并行执行后，无需等待结果，直接同步执行c的这种应用场景；只能选择同时执行a，b，b，这样会提交3个任务到线程池，而提交任务的主线程在闲置，对于高并发场景，有一定的性能损失，如果选择部分使用编排，会导致代码可读维护性下降，期待后续的改进
> \<chain name="test"\>
>     \<when value="a,b"/\> 
>     \<then value="c"/\>
> \</chain\>

感谢提出建议，我会加入issue

**Comment by xianyang-yang** [comment]
这两种写法应该是一样效果的吧？若果是，感觉前置/后置组件意义不是太大

```xml

<chain name="chain1">
    <pre value="p1,p2"/>
    <then value="a,b,c"/>
    <when value="d,e"/>
</chain>

<chain name="chain1">
    <then value="p1,p2"/>
    <then value="a,b,c"/>
    <when value="d,e"/>
</chain>

```

**Comment by bryan31** [comment]
> @xianyang-yang
> 这两种写法应该是一样效果的吧？若果是，感觉前置/后置组件意义不是太大
> 
> ```xml
> 
> <chain name="chain1">
>     <pre value="p1,p2"/>
>     <then value="a,b,c"/>
>     <when value="d,e"/>
> </chain>
> 
> <chain name="chain1">
>     <then value="p1,p2"/>
>     <then value="a,b,c"/>
>     <when value="d,e"/>
> </chain>
> 
> ```
> 
> 
> 
> 
> 

你代码所示的效果是一样的。但是前置组件不仅从语义上让在配置时一眼就看出来，而且即便你把前置组件定义在任何位置，他都会提前执行。当然你在最前面放一个then也是可以的。

如果说前置组件还可以通过把then放在最前面来替代，那么finally组件会显得更加有意义，无论任务链路正常执行还是报错，finally都会执行，其语义和java语法中的try finally一致。

**Comment by bryan31** [comment]
> @HengshengZ
> 请问下监控的处理逻辑能在哪里看到呢

目前监控逻辑比较简单，仅能打印每个组件的平均耗时。具体代码在`com.yomahub.liteflow.monitor.MonitorBus`

**Comment by jokiwei58** [comment]
<chain name="chain1">
    <then value="a,b,c"/>
    <when value="d,e"/>
</chain>

<chain name="chain1">
    <then value="a"/>
    <then value="b"/>
    <then value="c"/>
    <when value="d,e"/>
</chain>

多个then 和 <then value="a,b,c"/> 作用是一样的吗？

**Comment by bryan31** [comment]
> @jokiwei58
> ``` xml
> <chain name="chain1">
>     <then value="a,b,c"/>
>     <when value="d,e"/>
> </chain>
> 
> <chain name="chain1">
>     <then value="a"/>
>     <then value="b"/>
>     <then value="c"/>
>     <when value="d,e"/>
> </chain>
> ```
> 
> 
> 
> 多个then 和  then value="a,b,c" 作用是一样的吗？ 

你图示的例子是等同的

**Comment by LongCodeShort** [comment]
流式的编排在这种框架的话怎么写

**Comment by bryan31** [comment]
> @LongCodeShort
> 流式的编排在这种框架的话怎么写

能否举个例子
